//
//  CompData.swift
//  FblaSignUpPage
//
//  Created by Sid on 12/30/19.
//  Copyright © 2019 sid. All rights reserved.
//

import Foundation

struct FBLACompetitionsData{
    static let competitionTopics:[String] = ["Individual Objective", "Individual Oral", "Technology", "Prejudged", "Impromptu"]
    static let indivObjecComps:[CompData] = [
         CompData(subcategory: "Individual Objective", name:  "Accounting I", cluster:"Finance", summary: "The accurate keeping of financial records is an ongoing activity in all types of businesses. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of and skill in basic accounting principles and procedures."),
         CompData(subcategory: "Individual Objective", name:  "Accounting II",cluster:"Finance", summary: "The accurate keeping of financial records is a vital ongoing activity in all types of businesses. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of and skill in accounting principles and procedures as applied to sole proprietorships, partnerships, and corporations."),
         CompData(subcategory: "Individual Objective", name:  "Advertising", cluster:"Management & Marketing", summary: "Advertising is the promotion of a service or product of a company. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of different advertising practices as well as laws and ethics associated with them."),
         CompData(subcategory: "Individual Objective", name:  "Agribusiness",cluster:"Management & Marketing", summary: "Agribusiness is the industry of farming or agriculture. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of and skill in basic agribusiness concepts and procedures."),
         CompData(subcategory: "Individual Objective", name:  "Business Calculations",cluster:"Finance", summary:"Acquiring a high level of mathematics skill to solve business problems is a challenge for all prospective business employees. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of mathematical functions in business applications."),
         CompData(subcategory: "Individual Objective", name:  "Business Communication",cluster:"Business Writing", summary:"Learning to communicate in a manner that is clearly understood by the receiver of the message is a major task of all business people. This event is composed of a one-hour objective test. It recognizes FBLA members who work toward improving their business communication skills of writing, speaking, and listening."),
         CompData(subcategory: "Individual Objective", name:  "Business Law",cluster:"Economics & Law", summary: "Business law encompasses the law governing contracts, sales, commercial paper, agency and employment law, business organizations, property, and bailments. Business law may include issues such as starting, selling ,or buying a small business, managing a business, dealing with employees, or dealing with contracts, among others.This event is composed of a one-hour objective test. It recognizes FBLA members who are familiar with specific legal areas that most commonly affect personal and business relationships."),
         CompData(subcategory: "Individual Objective", name:  "Computer Applications",cluster:"Technology", summary:"Knowledge of computer applications is a necessity in today's high-tech business world. Employees must be able to apply various computer applications in a business environment utilizing critical thinking and decision-making skills. This event consists of two Data(cluster:2) parts: a school-site production test and an objective test. It recognizes FBLA members who can most efficiently demonstrate computer application skills."),
         CompData(subcategory: "Individual Objective", name:  "Computer Problem Solving",cluster:"Technology", summary:"Having a broad base of knowledge and competencies in core hardware and operating system technologies including installation, configuration, diagnostics, preventative maintenance, and basic networking is an important element for today’s computer savvy individual. A one-hour objective test will be administered at the conference based on the competencies listed. This event recognizes FBLA members who effectively manage hardware, software, and security of personal computers."),
         CompData(subcategory: "Individual Objective", name:  "Cyber Security",cluster:"Technology", summary:"With the increased use of the Internet for browsing, researching, information gathering, and e-commerce, information and cyber security has become a growing concern for businesses throughout our global economy. This event consists of a one-hour objective test. It recognizes FBLA members who understand security needs for technology."),
         CompData(subcategory: "Individual Objective", name:  "Database Design & Applications",cluster:"Technology", summary:"Databases are necessary to organize data and information in business. This event consists of two parts: a school-site production test and an objective test. It recognizes FBLA members who demonstrate that they have acquired entry-level skills for understanding database usage and development in business."),
         CompData(subcategory: "Individual Objective", name:  "Economics",cluster:"Economics & Law", summary: "Economics is about choice; individuals, businesses and governments are all faced with making choices regarding the allocation of scarce resources. As a result, economics is applicable in a wide range of fields, including business, finance, administration, law, local/national government and most aspects of everyday life. This event is composed of a one-hour objective test. It recognizes FBLA members who can identify, understand, and apply economic principles to contemporary social, political, and ecological problems."),
         CompData(subcategory: "Individual Objective", name:  "Health Care Administration",cluster:"Management & Marketing", summary: "Health care administrators manage the business side of health services, effectively managing resources to ensure the best medical care to the community. Health care administrators plan, coordinate, and supervise the functions of health care facilities and the staff that work there. This event is composed of a one-hour objective test. It recognizes FBLA members who are familiar with specific legal areas that most commonly affect personal and business relationships."),
         CompData(subcategory: "Individual Objective", name:  "Insurance & Risk Management",cluster:"Economics & Law", summary: "Insurance and risk management involves identifying and controlling an individual?s or business? exposure to loss or injury. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of and skill in basic insurance and risk management principles and procedures."),
         CompData(subcategory: "Individual Objective", name:  "Introduction to Business",cluster:"Management & Marketing", summary: "Part of running a business is the ability to identify, describe, analyze and evaluate the general objectives of the business and the context in which it operates. Businessmen and women understand the advantages and disadvantages of different forms of business and organizational structure, the source of financing available, data/information management, ethics, and the impact of global business on their business. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of introductory business concepts and vocabulary."),
         CompData(subcategory: "Individual Objective", name:  "Introduction to Business Communication",cluster:"Business Writing", summary: "Learning to communicate in a manner that is clearly understood by the receiver of the message is a major task of all business people. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of basic communication skills and concepts."),
         CompData(subcategory: "Individual Objective", name:  "Introduction to Business Procedures",cluster:"Management & Marketing", summary: "Competency in performing daily tasks is a necessity in business. This event is composed of a one-hour objective test. It recognizes FBLA members who possess knowledge of basic skills and procedures and the ability to make intelligent business decisions."),
         CompData(subcategory: "Individual Objective", name:  "Introduction to FBLA",cluster:"Management & Marketing", summary: "Members in FBLA should be knowledgeable about the association and the information found in the official publications. This event is composed of a one-hour objective test. It recognizes FBLA members who are interested in learning about the background and current information of FBLA. This competition was previously known as FBLA Principles and Procedures."),
         CompData(subcategory: "Individual Objective", name:  "Introduction to Financial Math",cluster:"Finance", summary: "Acquiring the ability to solve common business mathematical problems is a basic skill needed by all prospective business employees. This event is composed of a one-hour objective test. It recognizes FBLA members who have an understanding of basic math functions needed in business."),
         CompData(subcategory: "Individual Objective", name:  "Introdution to Information Technology",cluster:"Technology", summary: "Successful business leaders must understand the impact of technology and how to effectively harness it to drive business. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate acquired technology skills aligned with the Internet and Computing Core Certification Data(cluster:IC3) objectives."),
         CompData(subcategory: "Individual Objective", name:  "Introduction to Parliamentary Procedure",cluster:"Management & Marketing", summary: "Parliamentary procedure is the body of rules, ethics and customs that govern meetings of clubs and organizations. This event is composed of a one-hour objective test. It recognizes FBLA members who possess knowledge of basic skills and procedures and the ability to make intelligent business decisions."),
         CompData(subcategory: "Individual Objective", name:  "Journalism",cluster:"Business Writing", summary: "Journalism the activity of writing for newspapers or magazines or of broadcasting news on radio or television. This event is composed of a one-hour objective test. It recognizes FBLA members who are familiar with all aspects of journalism, including the history and ethics of it."),
         CompData(subcategory: "Individual Objective", name:  "Networking Concepts",cluster:"Technology", summary: "Most businesses implement a connected workplace to share resources over the network. Staying connected is vital to the smooth operation of businesses. This event is composed of a one-hour objective test. It recognizes FBLA members who have an understanding of network technologies."),
         CompData(subcategory: "Individual Objective", name:  "Organizational Leadership",cluster:"Management & Marketing", summary: "Leadership is necessary in the business world in order to successfully run a business. This event is composed of a one-hour objective test. It recognizes FBLA members who demonstrate an understanding of leadership concepts and communication skills."),
         CompData(subcategory: "Individual Objective", name:  "Personal Finance",cluster:"Finance", summary: "Financial literacy is essential in meeting the financial challenges of the 21st century. This event is composed of a one-hour objective test. It recognizes FBLA members who possess essential knowledge and skills related to financial issues, can analyze the rights and responsibilities of consumers, and apply knowledge to financial situations."),
         CompData(subcategory: "Individual Objective", name:  "Securities & Investments",cluster:"Economics & Law", summary: "Knowledge of securities and investments is an important part of constructing a lifetime strategy for meeting the challenges of saving and investing for the future. This event is composed of a one-hour objective test. It recognizes FBLA members who possess comprehensive knowledge of investment fundamentals; investment wrappers, taxation, and trusts; investment products and funds; the stock market; stock versus other investments; mutual funds; bonds; derivatives; and financial services regulation."),
         CompData(subcategory: "Individual Objective", name:  "Spreadsheet Applications",cluster:"Technology", summary: "Spreadsheet skills are necessary to convert data to information in business. This event consists of two parts: a school-site production test and an objective test. It recognizes FBLA members who demonstrate that they have acquired skills for spreadsheet development in business."),
         CompData(subcategory: "Individual Objective", name:  "Word Processing",cluster:"Technology", summary: "Word processing skills are necessary for all business leaders. This event consists of two parts: a school-site production test and an objective test. It recognizes FBLA members who demonstrate that they have acquired skills for spreadsheet development in business.")]
    
    static let indivOralComps:[CompData] = [
         CompData(subcategory: "Individual Oral", name:  "Client Service",cluster: "Speaking", summary: "This role play event requires the competitor to provide customer service to a client (judges). This event provides members with an opportunity to develop and demonstrate skills in interacting with internal and external clients to provide an outstanding client service experience. The client service consultant engages clients in conversations regarding products, handles inquiries, solves problems, and uncovers opportunities for additional assistance."),
         CompData(subcategory: "Individual Oral", name:  "Creed",cluster: "Speaking", summary: "The FBLA Creed Contest is designed to foster oratorical and thinking skills of students in presenting the FBLA Creed using public speaking techniques. This event consists of reciting the FBLA Creed. The FBLA Creed Contest is designed to foster oratorical and thinking skills of students in presenting the FBLA Creed using public speaking techniques."),
         CompData(subcategory: "Individual Oral", name:  "Electronic Career Portfolio",cluster: "Speaking", summary: "An electronic career portfolio is a purposeful collection of work that tells the story of an applicant including achievements, growth, vision, reflection, skills, experience, education, training, and career goals. It is a tool that gives employers a complete picture of who you are?your experience, your education, your accomplishments?and what you have the potential to become?much more than just a letter of application and r?sum? can provide. This event consists of two parts: a prejudged project and a presentation at the conference focusing on career research and student readiness."),
         CompData(subcategory: "Individual Oral", name:  "Future Business Leader",cluster: "Speaking", summary: "This event consists of three parts: a cover letter & r?sum?, an objective test, and an interview. This event honors outstanding FBLA members who demonstrate leadership qualities, participate actively in FBLA, and provide evidence of knowledge and skills essential for successful careers in business."),
         CompData(subcategory: "Individual Oral", name:  "Help Desk",cluster: "Speaking", summary: "The ability to provide technical assistance to the users of computer hardware and software is essential to the success of any organization and its continued operation. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate an understanding of and ability to provide technical assistance to end users."),
         CompData(subcategory: "Individual Oral", name:  "Impromptu Speaking",cluster: "Speaking", summary: "The ability to express one's thoughts without prior preparation is a valuable asset, as are poise, self-confidence, and organization of facts. This event consists of improvising a speech on a given topic related to one or more of the following: FBLA-PBL Goals, FBLA-PBL activities, FBLA-PBL current national programs, current events, and/or relevant business topics. It recognizes FBLA members who develop qualities of business leadership by combining quick and clear thinking with sound argumentation, strategic word choice, and engaged delivery."),
         CompData(subcategory: "Individual Oral", name:  "Introduction to Public Speaking",cluster: "Speaking", summary: "A person's self-confidence improves as he/she becomes an effective public speaker. Public speaking skills can be used to inform an audience, influence them to agree, and sometimes take action - all vital skills in the business environment. This event consists of a four (4) minute speech. The speech must be of a business nature and must be developed from one or more of the FBLA-PBL goals. It recognizes FBLA members who are beginning to develop qualities of business leadership by developing effective speaking skills."),
         CompData(subcategory: "Individual Oral", name:  "Job Interview",cluster: "Speaking", summary: "The job application and interview process plays a key role in determining whether the company and job candidate will make an effective match. The r?sum?, cover letter, and application give the interviewers an overview of the applicant?s background and skills; the interview gives the candidate a chance to make a favorable impression. This event consists of three parts: a cover letter & r?sum?, a job application, and an interview. It recognizes FBLA members who demonstrate proficiency in applying for employment in business."),
         CompData(subcategory: "Individual Oral", name:  "Public Speaking",cluster: "Speaking", summary: "A person's self-confidence improves as he/she becomes an effective public speaker. Public speaking skills can be used to inform an audience, influence them to agree, and sometimes take action - all vital skills in the business environment. This event consists of a five (5) minute speech. The speech must be of a business nature and must be developed from one or more of the FBLA-PBL goals. It recognizes FBLA members who, through public speaking, demonstrate qualities of business leadership by presenting a well-organized, logical, and substantial speech."),
         CompData(subcategory: "Individual Oral", name:  "Sales Presentation",cluster: "Speaking", summary: "Sales presentations are an important part of the sales process, allowing a company to convince potential customers to finalize a sale. This event consists of: A prejudged project based on the topic and a presentation to a panel of judges to sell a product of your choice. It recognizes FBLA members who develop and present a well-organized and convincing sales presentation.")]
    static let techComp: [CompData] = [
         CompData(subcategory: "Technology", name:  "3-D Animation",cluster: "N/A", summary: "3D animation is an effective way to represent complex concepts and ideas. This event consists of two parts: a prejudged project and a presentation at the conference. It recognizes FBLA members who demonstrate the ability to utilize 3D animation to create a video for a specific audience."),
         CompData(subcategory: "Technology", name:  "Coding and Programming",cluster: "N/A", summary: "Certain types of accounting processes require that each record in the file be processed. Coding and Programming focuses on these procedural style processing systems. This event consists of two parts: a prejudged project and a presentation at the conference. It tests the programmer?s skill in designing a useful, efficient, and effective program."),
         CompData(subcategory: "Technology", name:  "Computer Game & Simulation",cluster: "N/A", summary: "Interactive computer games and simulations have achieved broad acceptance and implementation in a wide variety of business and educational disciplines. Buried within many of these programs is a message that advances the player?s experience from simple entertainment to edutainment. This event consists of two parts: a prejudged project and a presentation at the conference. It tests the programmer?s skill in designing a functional interactive simulation/game that will both entertain and educate/inform the player."),
         CompData(subcategory: "Technology", name:  "Digital Video Production",cluster: "N/A", summary: "Digital video has become a prominent and effective way of conveying new ideas and products. This event consists of two parts: a prejudged project and a presentation at the conference. It recognizes FBLA members who demonstrate the ability to create an effective video to present an idea to a specific audience."),
         CompData(subcategory: "Technology", name:  "E-business",cluster: "N/A", summary: "One critical element in a business’ success in today’s global market is the ability to sell products and services to the consumer via the Internet. This event consists of two parts: a prejudged project and a presentation at the conference. This event recognizes FBLA members who have developed proficiency in the creation and design of Web commerce sites."),
         CompData(subcategory: "Technology", name:  "Graphic Design",cluster: "N/A", summary: "An essential part of today's business world is commercial graphic design; therefore, the preparation of computer-based digital art is paramount to the production of quality copy used for promotional purposes. This event consists of two parts: a prejudged project and a presentation at the conference. It recognizes FBLA members who demonstrate the ability to create an effective and aesthetic graphic design plan for a business."),
         CompData(subcategory: "Technology", name:  "Mobile Application Development",cluster: "N/A", summary: "Society is continually responding to a constant feed of communication, transfer of information, and the need to access or process information in a mobile environment. Mobile applications are necessary to provide users with the ability to be productive while away from their full computers. Mobile applications can be used as a lite version of something that would be done on a full computer, or they can provide a tool for something that users would only need to do on their phone. This event consists of two parts: a prejudged project and a presentation at the conference. It recognizes FBLA members who demonstrate the ability to create an effective and user-friendly mobile application."),
         CompData(subcategory: "Technology", name:  "Publication Design",cluster: "N/A", summary: "Knowledge of publication design is vital in many aspects of today?s visual business publications. This event consists of two parts: a prejudged project and a presentation at the conference. It provides recognition to FBLA members who can most effectively demonstrate skills in the areas of publication design, creativity, and decision-making."),
         CompData(subcategory: "Technology", name:  "Website Design",cluster: "N/A", summary: "The ability to communicate ideas and concepts, and to deliver value to customers using the Internet and related technologies is an important element in a business? success. This event consists of two parts: a prejudged project and a presentation at the conference. It recognizes FBLA members who have developed proficiency in the creation and design of websites.")]
    static let prejudgedComp: [CompData] = [
         CompData(subcategory: "Prejudged", name:  "Broadcast Journalism",cluster: "N/A", summary: "Broadcast news and events is essential to keeping business professionals and the public informed. Research and develop a news story for the given topic. You will write and submit a news broadcast for a fictitious news company prior to the conference. You will then prepare to perform a live 7-minute “broadcasting” of the report to a panel of judges at the State or National Leadership Conference. All types of visual aids (can be electronic, printed, etc.) are permitted during the presentation."),
         CompData(subcategory: "Prejudged", name:  "Business Ethics",cluster: "N/A", summary: "Ethical decisions are essential in the business world and the workplace. This team event consists of two parts: a prejudged written synopsis on the given topic and a presentation component. It recognizes FBLA members who demonstrate the ability to present solutions to ethical situations encountered in the business world and the workplace."),
         CompData(subcategory: "Prejudged", name:  "Business Financial Plan",cluster: "N/A", summary: "Business financial planning is paramount to the success of any business enterprise. This event consists of two parts: a prejudged report and a presentation at the conference. It is designed to recognize FBLA members who possess the knowledge and skills needed to establish and develop a complete financial plan for a business venture. The financial plan requesting a loan from a financial institution must be economically and financially sound with a realistic time frame. In addition to learning and applying financial business decision-making skills, team participants develop business contacts, implement written and oral skills, and develop familiarity with procedures of financial institutions."),
         CompData(subcategory: "Prejudged", name:  "Business Plan",cluster: "N/A", summary: "Business plans are an effective tool for evaluating, organizing, and selling a new business concept. A well-developed business plan can be a key component of a successful business start-up. This event consists of two parts: a prejudged report and a presentation at the conference. It recognizes FBLA members who demonstrate an understanding and mastery of the process required in developing and implementing a new business venture."),
         CompData(subcategory: "Prejudged", name:  "Emerging Business Issues",cluster: "N/A", summary: "This event provides FBLA members with an opportunity to develop and demonstrate skills in researching and presenting an emerging business issue. This event consists of two parts: a prejudged written synopsis and a presentation component for the topic listed taking both the affirmative and negative argument. It provides FBLA members with an opportunity to develop and demonstrate skills in researching and presenting an emerging business issue."),
         CompData(subcategory: "Prejudged", name:  "Introduction to Business Presentation",cluster: "N/A", summary: "Using technology to support a presentation can significantly enhance a business leader's effectiveness. This event consists of two parts: a prejudged presentation (slide deck file) on the given topic and a presentation component at the conference. It recognizes FBLA members who demonstrate the ability to deliver an effective business presentation while using multimedia presentation technology."),
         CompData(subcategory: "Prejudged", name:  "Public Service Announcement",cluster: "N/A", summary: "Public service ads (PSA) or public service announcements are basic messages to the public that raise awareness on a specific social issue. This event consists of two parts: a 30-second video based on the given topic and a presentation. It recognizes FBLA members who demonstrate the ability to research a topic (issue) and create an original and informative thirty-second PSA video, raising awareness and/or evoking a changed attitude toward the issue."),
         CompData(subcategory: "Prejudged", name:  "Social Media Campaign",cluster: "N/A", summary: "Social media is changing the way businesses communicate with customers and how they promote products and services. This event consists of two parts: a prejudged project and a presentation at the conference. It recognizes FBLA members who effectively use social media as a channel for a strategic marketing plan."),
         CompData(subcategory: "Prejudged", name:  "Virtual Business Financial Challenge",cluster: "N/A", summary: "Members will use this simulation to test their skills at managing their own financial lives and will compete against students across the country. Students file taxes, open bank accounts, apply for credit cards, monitor credit scores, apply for jobs, purchase insurance, and more. The online simulation is 100 percent web-based. This competition can be done by an individual or a team."),
         CompData(subcategory: "Prejudged", name:  "Virtual Business Management Challenge",cluster: "N/A", summary: "This event can be individual or have teams of up to three people. Members use highly visual simulation software (like SimCity) to manage a business. Students participate online for free and compete for the highest score against schools across the United States. This challenge encourages FBLA members to test their skills individually or as a team.")]
    static let impromptuComp:[CompData] = [
         CompData(subcategory: "Impromptu", name:  "Banking & Financial Systems",cluster: "N/A", summary: "Understanding how financial institutions and financial consulting and advisory services operate is important to successful business ownership and management, as well as to personal financial success. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate an understanding of and skill in the general operations of the various components of the financial service sector."),
         CompData(subcategory: "Impromptu", name:  "Entrepreneurship",cluster: "N/A", summary: "Owning and managing a business is the goal of many Americans. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate the knowledge and skills needed to establish and manage a business, which includes the management, marketing, and finance aspects of it."),
         CompData(subcategory: "Impromptu", name:  "Global Business",cluster: "N/A", summary: "The global economy is a complex, continually flowing and constantly changing network of information, goods, services, and cultures. Most nations rely on other nations for natural resources to supply their needs and wants. Global business also provides new markets and investment opportunities as well as promotion of better relationships. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate an understanding of and the skills needed to succeed in the global economy."),
         CompData(subcategory: "Impromptu", name:  "Hospitality Management",cluster: "N/A", summary: "Hospitality is the business of providing friendly and generous reception and entertainment to guests. This event consists of two parts: an objective test and a role play performance component. It provides recognition to FBLA members who have the ability to help other people enjoy both leisure and business travel and events."),
         CompData(subcategory: "Impromptu", name:  "Management Decision Making",cluster: "N/A", summary: "Making critical decisions that provide the right direction and a winning position in today's business world is essential to good management. Business executives must make high-quality, nearly instantaneous decisions all the time. The ability to make the right decisions concerning vision, growth, resources, strengths, and weaknesses leads to a successful business. It is management's responsibility to manage for today and tomorrow, to manage for optimum efficiency, and to manage to compete in the marketplace. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate knowledge of effective management strategies and the ability to make business decisions."),
         CompData(subcategory: "Impromptu", name:  "Management Information Systems",cluster: "N/A", summary: "The ability to design and implement an information system solution to effectively manage vast amounts of information is a valuable skill that leads to the success of many business entities today. The use of technology to develop these information systems plays a crucial role in a business? ability to compete in today?s business environment. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate an understanding of and ability to apply these skills."),
         CompData(subcategory: "Impromptu", name:  "Marketing",cluster: "N/A", summary: "Marketing involves the distribution of products and services to the consumer. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who possess knowledge of the basic principles of marketing."),
         CompData(subcategory: "Impromptu", name:  "Network Design",cluster: "N/A", summary: "The ability to evaluate the needs of an organization and then design and implement network solutions is a valuable skill in today?s connected workplace. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate an understanding of and ability to apply these skills."),
         CompData(subcategory: "Impromptu", name:  "Parliamentary Procedure",cluster: "N/A", summary: "Parliamentary Procedures refers to the body of rules, ethics, and customs governing meetings and operations of deliberative assemblies. The core idea of Parliamentary Procedures revolves around how to protect the will of the majority whilst simultaneously respecting the minority. As a result, it is a great competitive opportunity for leaders who are interested in learning how to properly run any kind of meeting, especially in American politics and government. This event consists of two parts: an objective test and a role play performance component. It recognizes FBLA members who demonstrate knowledge of the principles of parliamentary procedure."),
         CompData(subcategory: "Impromptu", name:  "Sports & Entertainment Management",cluster: "N/A", summary: "The sports industry is rapidly growing in this country and throughout the world. For an individual to be successful and effective in this type of work, a core understanding of business and a comprehensive awareness of sports is necessary to succeed in sports management. This event consists of two parts: an objective test and a role play performance component. This event recognizes FBLA members who possess the basic principles of sports management.")]


}

class CompData{
    var cluster : String?
    var summary : String?
    var name    : String?
    var subCat  : String?
    init(subcategory: String, name:  String, cluster: String, summary: String) {
        self.cluster    = cluster
        self.summary    = summary
        self.name       = name
        self.subCat     = subcategory
    }
    func getCluster()   -> String{ return cluster!  }
    func getSummary()   -> String{ return summary!  }
    func getName()      -> String{ return name!     }
    func getSub()       -> String{ return subCat!   }
}


